# Generated by Django 3.1 on 2020-09-18 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_App', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_addr', models.CharField(max_length=50)),
                ('customer_contact', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_code', models.CharField(max_length=50)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=80)),
                ('offer_id', models.IntegerField()),
                ('offer_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_date_time', models.DateTimeField()),
                ('category_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.PositiveIntegerField()),
                ('product_price_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_App.gst')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_App.product_info')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date_time', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_App.customer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_App.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_App.product')),
            ],
        ),
    ]
