# Generated by Django 3.1 on 2020-09-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('vendor_contact', models.IntegerField()),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('product_expiry_date', models.DateField()),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_App.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_App.vendor')),
            ],
        ),
    ]
